# Namespace definition
apiVersion: v1
kind: Namespace
metadata:
  name: guessing-game
---
# ConfigMap definition
apiVersion: v1
kind: ConfigMap
metadata:
  name: guessing-game-config
  namespace: guessing-game
data:
  TARGET_NUMBER: "42"
  PORT: "5000"
---
# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guessing-game
  namespace: guessing-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guessing-game
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: guessing-game
    spec:
      containers:
      - name: guessing-game
        image: ibraheemcisse/python-guessing-game:latest  
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: guessing-game-config
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
# Service definition
apiVersion: v1
kind: Service
metadata:
  name: guessing-game
  namespace: guessing-game
spec:
  selector:
    app: guessing-game
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
