deploy:
  needs: build-and-push
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Minikube
      run: |
        # Install Minikube
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

        # Start Minikube with enough resources
        minikube start --cpus=4 --memory=8192

        # Set kubectl to use Minikube's context
        kubectl config use-context minikube

    - name: Configure kubeconfig
      run: |
        # Ensure kubectl is pointing to Minikube's config
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Update Kubernetes deployment image
      run: |
        # Update image in deployment YAML
        sed -i "s|image:.*|image: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml
        
        # Apply Kubernetes manifests
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        
        # Verify deployment
        kubectl get pods -n ${{ env.K8S_NAMESPACE }}
        kubectl rollout status deployment/guessing-game -n ${{ env.K8S_NAMESPACE }}

